### ISSUE TITLE
Password persisted

### ISSUE THREAD

**Issue by mindfarm** [zaibon/ircbot#2]
Hi

I know that this is old example code, but I want to point out (should anyone be using this code to get themselves started) that there's absolutely NO need to persist the password in the code

https://github.com/zaibon/ircbot/blob/master/bot.go#L26

Instead, all that is needed is for the password to be read from the ENV and passed to the identify method when it's called

**Comment by zaibon** [comment]
Thanks for the recommendation. This is has been fixed in https://github.com/zaibon/ircbot/pull/4
